### PR TITLE
Nix flakes

### PR DESCRIPTION
**Pull request by InfiniteCoder01**
Adds flake for nix package manager

### CODE REVIEW

**Comment by InfiniteCoder01** [comment]
Note: flake.lock should be present in the repository for better reproduceability

**Comment by InfiniteCoder01** [comment]
Please, review

**Comment by MihailRis** [comment]
- What is it for (in the project context) and is this worth further support?
- How does it work with dependencies (especially - *entt*)?

**Comment by InfiniteCoder01** [comment]
1. Nix - cross-platform package management solution (and only way to manage packages on NixOS). Works by specifying list of dependencies and tools required to maintain a piece of software, locking them for reproducibility.
2. All dependencies (including enTT, which is already in) are specified in flake.nix file. Dependencies that are not packaged with nix packages (that's rare) can be imported as other flakes straight from github. If there is no existing nix solution for a certain dependency, it's possible to package it manually, as Nix is a functional programming language.

**Pull request merged**
